"""create sstuff

Revision ID: 435fc1ec8d59
Revises: 
Create Date: 2024-04-09 16:13:27.721359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435fc1ec8d59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genres')
    op.drop_table('artists')
    # ### end Alembic commands ###
